name: Publish - Jinx Updates
on:
  workflow_dispatch:
    inputs:
      mapDBCommitHash:
        description: 'Force checkout of map to HASH version'
        required: false
  push:
    branches:
    - master

permissions:
  contents: write

jobs:
  mirror:
    if: "!contains(github.event.head_commit.message, 'Repo updates within last')"
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout configuration
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Update JINX manifest
        continue-on-error: true
        run: |
          wget --tries=5 --retry-connrefused --retry-on-host-error https://github.com/elanthia-online/jinxp/releases/download/v0.4.0/jinxp \
          && chmod +x jinxp \
          && ./jinxp -i scripts
          sed -i 's|/assets/|/scripts/|g' dist/manifest.json
          mv dist/manifest.json ./
          mv dist/headers ./

      - name: Commit changes
        continue-on-error: true
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add headers
          git add manifest.json
          if [ -z "$(git status --porcelain)" ]; then 
            echo "No changes to commit"
          else 
            git commit -m "Repo updates within last 3 hours"
          fi

      - name: Push changes
        if: steps.check_changes.outputs.has_changes == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
